adoption:
    resource: "@AdoptionBundle/Resources/config/routing.yml"
    prefix:   /

soin:
    resource: "@soinBundle/Resources/config/routing.yml"
    prefix:   /

events:
    resource: "@eventsBundle/Resources/config/routing.yml"
    prefix:   /

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /

vente:
    resource: "@VenteBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

template:
    resource: "@TemplateBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messages

genj_faq:
    resource: "@GenjFaqBundle/Resources/config/routing.yml"