<?php

namespace AdoptionBundle\Repository;

/**
 * RefugeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefugeRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheRefuge($libelle)
    {
        $q=$this->getEntityManager()->createQuery("select v from AdoptionBundle:Refuge v where 
            v.libelle=:libelle ")
            ->setParameter('libelle',$libelle);
        return $q->getResult();

    }
    public function rechercheById($id)
    {
        $q=$this->getEntityManager()->createQuery("select a from AdoptionBundle:Refuge a where a.id=:id")
            ->setParameter('id',$id);
        return $q->getResult();
    }
}
