<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function selectuser($username)
    {

        $req=$this->getEntityManager()->createQuery("select u.id,u.username,u.password from UserBundle:User u where u.username=:username")
            ->setParameter(':username',$username);

        return $req->getResult();

    }
}
