<?php

namespace soinBundle\Repository;

/**
 * centreToilettageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class centreToilettageRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheAjax($mot)
    {
        $q=$this->getEntityManager()->createQuery("select c from soinBundle:centreToilettage c where 
            c.adresse like :mot  OR c.libelle like :mot OR c.tel like :mot OR c.description like :mot ")
            ->setParameter('mot',"%$mot%");
        return $q->getResult();

    }

}
