<?php

namespace soinBundle\Repository;
use Symfony\Component\Form\DataTransformerInterface;

/**
 * reservationVeterinaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservationVeterinaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function existance ($dated,$id)
    {

        $events=$this->getEntityManager()
            ->createQuery('SELECT r FROM  soinBundle:reservationVeterinaire r 
		WHERE r.id_veterinaire = :id and :dated BETWEEN  r.date_debut AND r.date_fin ')
            ->setParameter("id",$id)
            ->setParameter("dated",$dated);
        return $events->getResult();
        // var_dump($events->getResult());
    }






    // doctrine query langage DQL
    public function findByRole($role)
    {
        $q = $this->getEntityManager()->createQueryBuilder();
        $q->select('u')
            ->from('UserBundle:User', 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"' .$role.'"%');
        return $q->getQuery()->getResult();
    }
    /* les drv d'un veterinaire */

    public function aficher_rdv($id)
    {
        $q = $this->getEntityManager()->createQueryBuilder();
        $q->select('u')
            ->from('soinBundle:reservationVeterinaire', 'u')
            ->where('u.id_veterinaire =:id')
            ->andWhere('u.date_debut > current_date() ')

            ->setParameter('id', $id);
        return $q->getQuery()->getResult();
    }

    /* rdv d'un membre */
    public function aficher_rdv_pris($id)
    {
        $q = $this->getEntityManager()->createQueryBuilder();
        $q->select('u')
            ->from('soinBundle:reservationVeterinaire', 'u')
            ->where('u.id_user =:id')
            ->andWhere('u.date_debut > current_date() ')

            ->setParameter('id', $id);
        return $q->getQuery()->getResult();
    }
}
