<?php

namespace ServiceBundle\Repository;

/**
 * CentreDressageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreDressageRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheAjax($mot)
    {
        $q=$this->getEntityManager()->createQuery("select c from ServiceBundle:CentreDressage c where 
                c.libelle LIKE :mot OR c.adresse LIKE :mot OR c.tel LIKE :mot OR c.description LIKE :mot")
            ->setParameter('mot',"%$mot%");
        return $q->getResult();

    }
}
