<?php

namespace ServiceBundle\Repository;

/**
 * ReservationPetsitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationPetsitterRepository extends \Doctrine\ORM\EntityRepository
{
    public function afficherReservation($idU)
    {
       $q=$this->getEntityManager()->createQuery("SELECT r FROM ServiceBundle:ReservationPetsitter r WHERE 
            r.idUser=:idU ")
           ->setParameter('idU',$idU);
        return $q->getResult();
    }

    public function apportPetsitter()
    {
        $q=$this->getEntityManager()->createQuery("SELECT IDENTITY(r.idPetsitter),SUM(r.encaisser) FROM ServiceBundle:ReservationPetsitter r GROUP BY r.idPetsitter  ");
        return $q->getResult();
    }

    public function TotalPetsitter()
    {
        $q=$this->getEntityManager()->createQuery("SELECT SUM(r.encaisser) FROM ServiceBundle:ReservationPetsitter r  ");
        return $q->getResult();
    }

    public function Petsitter()
    {
        $q=$this->getEntityManager()->createQuery("SELECT u FROM UserBundle:User u WHERE u.roles LIKE '%ROLE_PETSITTER%'  ");
        return $q->getResult();
    }

    public function rechercheAjax($mot)
    {
        $q=$this->getEntityManager()->createQuery("select r from ServiceBundle:ReservationPetsitter r where 
                r.date LIKE :mot OR r.prix LIKE :mot OR r.encaisser LIKE :mot OR IDENTITY(r.idPetsitter) LIKE :mot OR IDENTITY(r.idUser) LIKE :mot")
            ->setParameter('mot',"%$mot%");
        return $q->getResult();

    }

    public function existance ($dated,$id)
    {
        $q=$this->getEntityManager()
            ->createQuery('SELECT r FROM  ServiceBundle:ReservationPetsitter r 
		WHERE IDENTITY(r.idPetsitter) = :id and :dated BETWEEN  r.dateDebut AND r.dateFin ')
            ->setParameter("id",$id)
            ->setParameter("dated",$dated);
        return $q->getResult();
    }
}
