<?php

namespace eventsBundle\Repository;

/**
 * conseilsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class conseilsRepository extends \Doctrine\ORM\EntityRepository
{
}
