<?php

namespace eventsBundle\Repository;

/**
 * onseilsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class onseilsRepository extends \Doctrine\ORM\EntityRepository
{
}
