<?php

namespace eventsBundle\Repository;

/**
 * participationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participationRepository extends \Doctrine\ORM\EntityRepository
{
    public function calculerPart()
    {
        $q=$this->getEntityManager()->createQuery("SELECT IDENTITY (p.idc),COUNT (IDENTITY (p.idp)) FROM eventsBundle:participation p GROUP BY p.idc");
        return $q->getResult();
    }
}
