<?php

namespace VenteBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function affichageCategorie()
    {
        $req=$this->getEntityManager()->createQuery("select c from VenteBundle:Categorie c");
        return $req->getResult();
    }
}
