<?php

namespace VenteBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function affichage()
    {
        $req=$this->getEntityManager()->createQuery("select p from VenteBundle:Produit p");
        return $req->getResult();
    }

    public function Details($id)
    {
        $req=$this->getEntityManager()->createQuery("select p from VenteBundle:Produit p where p.id=:id")->setParameter('id',$id);
        return $req->getResult();
    }
    public function rechercheAjax($mot)
    {
        $q=$this->getEntityManager()->createQuery("select p from VenteBundle:produit p where 
                p.libelle LIKE :mot OR p.description LIKE :mot OR p.prix LIKE :mot OR p.animal LIKE :mot OR p.quantite LIKE :mot OR IDENTITY(p.categorie) LIKE :mot OR p.Image LIKE :mot")
            ->setParameter('mot',"%$mot%");
        return $q->getResult();

    }


}
